---
stages:
  - build
  - deploy

variables:
  PROJECT_ID: $GCLOUD_PROJECT_ID
  GOOGLE_APPLICATION_CREDENTIALS: $GCLOUD_SERVICE_KEY_FILE
  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE_NAME: $DOCKER_USERNAME/serverless-frontend

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_HOST: tcp://docker:2376
    DOCKER_CLI_EXPERIMENTAL: enabled  
  script:
    - cd frontend
    - echo "Checking Docker Daemon"
    - docker info || true
    - echo "Checking Docker Daemon Connectivity"
    - curl --unix-socket /var/run/docker.sock http://localhost/_ping || true
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker build -t $DOCKER_IMAGE_NAME:latest .
    - docker push $DOCKER_IMAGE_NAME:latest
  only:
    - dev

deploy:
  image: google/cloud-sdk:slim
  stage: deploy
  dependencies:
    - build
  script:
    - cd infra
    - gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
    - gcloud config set project $PROJECT_ID
    - gcloud auth configure-docker
    - gcloud services enable containerregistry.googleapis.com
    - gcloud services enable run.googleapis.com
    - gcloud services enable cloudbuild.googleapis.com
    - gcloud services enable deploymentmanager.googleapis.com
    - gcloud builds submit --region=us-central1 --config frontend_cloudbuild.yml
    - gcloud beta run services add-iam-policy-binding serverless-frontend --region=us-central1 --member=allUsers --role=roles/run.invoker
  only:
    - dev
