  steps:
  # Deploy docker image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'serverless-frontend'
    - '--image'
    - 'gcr.io/$PROJECT_ID/serverless-frontend:latest'
    - '--region'
    - 'us-central1'
    - '--port'
    - '443'